
### 数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
  ### thymeleaf相关配置
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    content-type: text/html
    mode: HTML5

  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /static/**
